/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArbitrageSignal {
  'action' : string,
  'reasoning' : string,
  'timestamp' : Time,
  'feesConsidered' : number,
  'spreadPercent' : number,
  'pairId' : string,
}
export interface DEXConfig {
  'id' : bigint,
  'tradingPairs' : Array<PairConfig>,
  'name' : string,
  'canisterId' : string,
}
export interface DecisionEvent {
  'result' : string,
  'step' : string,
  'timestamp' : Time,
  'details' : string,
}
export interface PairConfig {
  'feeBps' : bigint,
  'quoteSymbol' : string,
  'baseSymbol' : string,
  'poolId' : string,
}
export interface PriceSnapshot {
  'reserves' : [] | [[number, number]],
  'timestamp' : Time,
  'price' : number,
  'rawResponse' : string,
  'pairId' : string,
  'dexName' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addDEXConfig' : ActorMethod<[string, string, Array<PairConfig>], bigint>,
  'getAllDEXConfigs' : ActorMethod<[], Array<DEXConfig>>,
  'getDecisionHistory' : ActorMethod<[], Array<DecisionEvent>>,
  'getSortedDEXConfigs' : ActorMethod<[], Array<DEXConfig>>,
  'recordPriceSnapshot' : ActorMethod<[PriceSnapshot], undefined>,
  'runArbitrageAnalysis' : ActorMethod<[string], ArbitrageSignal>,
  'setDEXConfigStatus' : ActorMethod<[bigint, boolean], undefined>,
  'startAgent' : ActorMethod<[], undefined>,
  'stopAgent' : ActorMethod<[], undefined>,
  'updateTradingPairs' : ActorMethod<[bigint, Array<PairConfig>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];