/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PairConfig = IDL.Record({
  'feeBps' : IDL.Nat,
  'quoteSymbol' : IDL.Text,
  'baseSymbol' : IDL.Text,
  'poolId' : IDL.Text,
});
export const DEXConfig = IDL.Record({
  'id' : IDL.Nat,
  'tradingPairs' : IDL.Vec(PairConfig),
  'name' : IDL.Text,
  'canisterId' : IDL.Text,
});
export const Time = IDL.Int;
export const DecisionEvent = IDL.Record({
  'result' : IDL.Text,
  'step' : IDL.Text,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const PriceSnapshot = IDL.Record({
  'reserves' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
  'timestamp' : Time,
  'price' : IDL.Float64,
  'rawResponse' : IDL.Text,
  'pairId' : IDL.Text,
  'dexName' : IDL.Text,
});
export const ArbitrageSignal = IDL.Record({
  'action' : IDL.Text,
  'reasoning' : IDL.Text,
  'timestamp' : Time,
  'feesConsidered' : IDL.Float64,
  'spreadPercent' : IDL.Float64,
  'pairId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDEXConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(PairConfig)],
      [IDL.Nat],
      [],
    ),
  'getAllDEXConfigs' : IDL.Func([], [IDL.Vec(DEXConfig)], []),
  'getDecisionHistory' : IDL.Func([], [IDL.Vec(DecisionEvent)], ['query']),
  'getSortedDEXConfigs' : IDL.Func([], [IDL.Vec(DEXConfig)], ['query']),
  'recordPriceSnapshot' : IDL.Func([PriceSnapshot], [], []),
  'runArbitrageAnalysis' : IDL.Func([IDL.Text], [ArbitrageSignal], []),
  'setDEXConfigStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'startAgent' : IDL.Func([], [], []),
  'stopAgent' : IDL.Func([], [], []),
  'updateTradingPairs' : IDL.Func([IDL.Nat, IDL.Vec(PairConfig)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PairConfig = IDL.Record({
    'feeBps' : IDL.Nat,
    'quoteSymbol' : IDL.Text,
    'baseSymbol' : IDL.Text,
    'poolId' : IDL.Text,
  });
  const DEXConfig = IDL.Record({
    'id' : IDL.Nat,
    'tradingPairs' : IDL.Vec(PairConfig),
    'name' : IDL.Text,
    'canisterId' : IDL.Text,
  });
  const Time = IDL.Int;
  const DecisionEvent = IDL.Record({
    'result' : IDL.Text,
    'step' : IDL.Text,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const PriceSnapshot = IDL.Record({
    'reserves' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
    'timestamp' : Time,
    'price' : IDL.Float64,
    'rawResponse' : IDL.Text,
    'pairId' : IDL.Text,
    'dexName' : IDL.Text,
  });
  const ArbitrageSignal = IDL.Record({
    'action' : IDL.Text,
    'reasoning' : IDL.Text,
    'timestamp' : Time,
    'feesConsidered' : IDL.Float64,
    'spreadPercent' : IDL.Float64,
    'pairId' : IDL.Text,
  });
  
  return IDL.Service({
    'addDEXConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(PairConfig)],
        [IDL.Nat],
        [],
      ),
    'getAllDEXConfigs' : IDL.Func([], [IDL.Vec(DEXConfig)], []),
    'getDecisionHistory' : IDL.Func([], [IDL.Vec(DecisionEvent)], ['query']),
    'getSortedDEXConfigs' : IDL.Func([], [IDL.Vec(DEXConfig)], ['query']),
    'recordPriceSnapshot' : IDL.Func([PriceSnapshot], [], []),
    'runArbitrageAnalysis' : IDL.Func([IDL.Text], [ArbitrageSignal], []),
    'setDEXConfigStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'startAgent' : IDL.Func([], [], []),
    'stopAgent' : IDL.Func([], [], []),
    'updateTradingPairs' : IDL.Func([IDL.Nat, IDL.Vec(PairConfig)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };