/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ArbitrageSignal {
    action: string;
    reasoning: string;
    timestamp: Time;
    feesConsidered: number;
    spreadPercent: number;
    pairId: string;
}
export interface PairConfig {
    feeBps: bigint;
    quoteSymbol: string;
    baseSymbol: string;
    poolId: string;
}
export interface DEXConfig {
    id: bigint;
    tradingPairs: Array<PairConfig>;
    name: string;
    canisterId: string;
}
export type Time = bigint;
export interface DecisionEvent {
    result: string;
    step: string;
    timestamp: Time;
    details: string;
}
export interface PriceSnapshot {
    reserves?: [number, number];
    timestamp: Time;
    price: number;
    rawResponse: string;
    pairId: string;
    dexName: string;
}
export interface backendInterface {
    addDEXConfig(name: string, canisterId: string, tradingPairs: Array<PairConfig>): Promise<bigint>;
    getAllDEXConfigs(): Promise<Array<DEXConfig>>;
    getDecisionHistory(): Promise<Array<DecisionEvent>>;
    getSortedDEXConfigs(): Promise<Array<DEXConfig>>;
    recordPriceSnapshot(snapshot: PriceSnapshot): Promise<void>;
    runArbitrageAnalysis(pairId: string): Promise<ArbitrageSignal>;
    setDEXConfigStatus(dexId: bigint, isActive: boolean): Promise<void>;
    startAgent(): Promise<void>;
    stopAgent(): Promise<void>;
    updateTradingPairs(dexId: bigint, newTradingPairs: Array<PairConfig>): Promise<void>;
}
import type { PriceSnapshot as _PriceSnapshot, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDEXConfig(arg0: string, arg1: string, arg2: Array<PairConfig>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDEXConfig(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDEXConfig(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllDEXConfigs(): Promise<Array<DEXConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDEXConfigs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDEXConfigs();
            return result;
        }
    }
    async getDecisionHistory(): Promise<Array<DecisionEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDecisionHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDecisionHistory();
            return result;
        }
    }
    async getSortedDEXConfigs(): Promise<Array<DEXConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedDEXConfigs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedDEXConfigs();
            return result;
        }
    }
    async recordPriceSnapshot(arg0: PriceSnapshot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPriceSnapshot(to_candid_PriceSnapshot_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPriceSnapshot(to_candid_PriceSnapshot_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async runArbitrageAnalysis(arg0: string): Promise<ArbitrageSignal> {
        if (this.processError) {
            try {
                const result = await this.actor.runArbitrageAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runArbitrageAnalysis(arg0);
            return result;
        }
    }
    async setDEXConfigStatus(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDEXConfigStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDEXConfigStatus(arg0, arg1);
            return result;
        }
    }
    async startAgent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startAgent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startAgent();
            return result;
        }
    }
    async stopAgent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stopAgent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopAgent();
            return result;
        }
    }
    async updateTradingPairs(arg0: bigint, arg1: Array<PairConfig>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTradingPairs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTradingPairs(arg0, arg1);
            return result;
        }
    }
}
function to_candid_PriceSnapshot_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceSnapshot): _PriceSnapshot {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reserves?: [number, number];
    timestamp: Time;
    price: number;
    rawResponse: string;
    pairId: string;
    dexName: string;
}): {
    reserves: [] | [[number, number]];
    timestamp: _Time;
    price: number;
    rawResponse: string;
    pairId: string;
    dexName: string;
} {
    return {
        reserves: value.reserves ? candid_some(value.reserves) : candid_none(),
        timestamp: value.timestamp,
        price: value.price,
        rawResponse: value.rawResponse,
        pairId: value.pairId,
        dexName: value.dexName
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
